# Dockerfile for running frontend tests
FROM node:20-alpine
WORKDIR /app
COPY package.json .
COPY vite.config.js .
COPY vitest.config.js .
COPY tailwind.config.js .
COPY postcss.config.js .
COPY ./src ./src
RUN npm install
CMD ["npm", "run", "test"]
